Repository JFHaataja/student-council-website, pull requests merged in 2025-04, with the labels that each got.

#10 Create muokkaus.txt
  muokkaus.txt
Labels: documentation

#11 Luotu index.html-tiedosto
  index.html
Labels: enhancement

#12 Create uusitxt.txt
  uusitxt.txt
Labels: bug

#13 Release v1.1
  index.html
Labels: enhancement

#14 Create jasenlomake.php AB#32
  jasenlomake.php
  jasentietokanta
  yhteydenottolomake.php
Labels: enhancement

#15 Jon/navigointipalkki ja sivukartta / Fixed AB#27
  index.html
Labels: enhancement

#19 Create yhteydenottolomake_kayttoliittyma.php AB#32
  yhteydenottolomake_kayttoliittyma.php
Labels: enhancement

#18 Lisätty FAQ-osio etusivulle / Fixes AB#51
  index.html
Labels: enhancement

#22 Jon/tapahtumakalenteri / Fixes AB#28, Fixes AB#36, Fixes AB#43
  index.html
Labels: enhancement

#21 Create Blogi AB#30
  Blogi
Labels: enhancement

#20 Muokattu kuvagalleriaa AB#31
  index.html
Labels: enhancement
